chore: general codebase tooling (#42)
* chore: kover, detekt, spotless, abicheck
* chore: api pins for main package
* chore: detekt baselines
* chore: update gradle lockfiles
* chore: update gradle verification metadata
* chore: fmt pt 1 (manual, sorting)
* chore: reformat imports/kt sources from idea
* chore: fmt settings, pt 1
* chore: fmt java
* chore: swap `ktfmt` for `ktlint` and `.editorconfig`
* chore: fmt settings, pt 2
* chore: fmt kotlin
* chore: fmt kotlin gradle
* fix: drop duplicated formatting plugin
* chore: configure detekt
* chore: lock-resolve-all task
* fix: restore kotlin `2.1.0` (tmp)
* chore: update gradle lockfiles and metadata
* chore: coverage and test reporting
* chore: make claude reviews opt-in with `ai-review` label
* fix: codecov token access for workflows
* fix: audit mode for build in ci
* chore: upgrade gradle to `9.0.0-rc-3`
* fix: add missing `assemble` meta-task
* chore: upgrade foojay
* chore: upgrade kotlin to `2.2.0`
* chore: toolchain to jdk24
* fix: atomicfu plugin, coverage tweaks
* fix: trust pom files
* chore: update gradle verification metadata & lockfiles
* chore: make pr/push jobs runnable via `workflow_dispatch`
* fix: align ci with toolchain at oracle gvm 24
* fix: `checks` permission for reusable ci workflows

---------

Signed-off-by: Sam Gammon <sam@elide.dev>

diff --git a/.github/workflows/job.build.yml b/.github/workflows/job.build.yml
--- a/.github/workflows/job.build.yml
+++ b/.github/workflows/job.build.yml
@@ -64,6 +64,9 @@ on:
       GRADLE_ENCRYPTION_KEY:
         description: "Gradle Encryption Key"
         required: false
+      CODECOV_TOKEN:
+        description: "Codecov Token"
+        required: true
 
 permissions:
   contents: read
@@ -79,6 +82,7 @@ jobs:
     runs-on: ${{ inputs.runner || vars.RUNNER_DEFAULT || 'ubuntu-latest' }}
     permissions:
       contents: read
+      checks: write
     outputs:
       hashes: ${{ steps.hash.outputs.hashes }}
     steps:
@@ -86,7 +90,7 @@ jobs:
         uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
         with:
           disable-sudo: true
-          egress-policy: block
+          egress-policy: audit
           allowed-endpoints: >
             api.azul.com:443
             api.github.com:443
@@ -114,8 +118,8 @@ jobs:
       - name: "Setup: JVM"
         uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
         with:
-          java-version: ${{ vars.JAVA_TOOLCHAIN_VERSION || '21' }}
-          distribution: ${{ vars.JAVA_TOOLCHAIN_VENDOR || 'zulu' }}
+          java-version: ${{ vars.JAVA_TOOLCHAIN_VERSION || '24' }}
+          distribution: ${{ vars.JAVA_TOOLCHAIN_VENDOR || 'graalvm' }}
       - name: "Setup: Elide"
         uses: elide-dev/setup-elide@a62ce5ca052e16ecd1c6eb3f2efde2e0228d5e80 # main
       - name: "Setup: Gradle"
@@ -133,6 +137,22 @@ jobs:
         run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
       - name: "Build: Gradle"
         run: ./gradlew --scan build test check
+      - name: "Report: Tests (GHA)"
+        uses: elide-tools/action-junit-report@d8d34855fefcfd2a15b5005b4cca125da5b41c8c
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+      - name: "Report: Tests (Codecov)"
+        if: ${{ !cancelled() }}
+        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+      - name: "Report: Coverage (Codecov)"
+        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
+        with:
+          files: ./*/build/reports/kover/report.xml
+          token: ${{ secrets.CODECOV_TOKEN }}
+          verbose: true
       - name: "Artifact: Maven Repository"
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
         with:
